[dev]
  targetPort = 3000
  functionsPort = 9999 # optional but recommended to isolate function logs


[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200